spring.application.name=service-registry
server.port=8761

# Prevent the registry server from attempting to register with itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
