spring.application.name=executor-service
server.port=8086

# Redis Configuration (Upstash Cloud)
spring.data.redis.url=rediss://default:gQAAAAAAAnpIAAIgcDExNjMyYTNmYzRjM2I0MTFiOWZjYzQ2MjdmNjg0MDM0MQ@aware-gator-162376.upstash.io:6379
spring.data.redis.timeout=5000ms

# Kafka Producer
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Kafka Topics
job.run-events-topic=job-run-events
job.retry-topic=retry
job.dead-topic=dead

# Executor Settings
executor.id=executor-8086
executor.heartbeat-interval-ms=10000
executor.heartbeat-ttl-seconds=30
executor.default-timeout-seconds=60

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Logging
logging.level.com.zensys=TRACE
