spring.application.name=watcher-service
server.port=8084

# PostgreSQL (Supabase)
spring.datasource.url=jdbc:postgresql://db.gfidbklzztavhchntmcg.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=ZenSys2498#
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Kafka Producer
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Watcher Configuration
watcher.polling.interval-ms=20000
watcher.batch-size=1000
watcher.lock-threshold-seconds=30
watcher.run-topic=run

# Upstash Redis Configuration
spring.data.redis.url=rediss://default:gQAAAAAAAnpIAAIgcDExNjMyYTNmYzRjM2I0MTFiOWZjYzQ2MjdmNjg0MDM0MQ@aware-gator-162376.upstash.io:6379
spring.data.redis.timeout=5000ms

# Zombie Sweeper & Recovery Configuration
watcher.retry-topic=retry
watcher.job-run-events-topic=job-run-events
watcher.dead-topic=dead
watcher.zombie-sweeper.interval-ms=20000
watcher.zombie-sweeper.threshold-seconds=60
watcher.zombie-sweeper.batch-size=100

# Task Scheduler Thread Pool (Parallelizes @Scheduled tasks)
spring.task.scheduling.pool.size=4
spring.task.scheduling.thread-name-prefix=watcher-sched-
spring.threads.virtual.enabled=false

#Logging
logging.level.com.zensys=TRACE