spring.application.name=retry-service
server.port=8087

# Upstash Redis Configuration
spring.data.redis.url=rediss://default:gQAAAAAAAnpIAAIgcDExNjMyYTNmYzRjM2I0MTFiOWZjYzQ2MjdmNjg0MDM0MQ@aware-gator-162376.upstash.io:6379
spring.data.redis.timeout=5000ms

# Kafka Broker
spring.kafka.bootstrap-servers=localhost:9092

# Kafka Consumer Configuration (for 'retry' topic)
spring.kafka.consumer.group-id=retry-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.value.default.type=com.zensys.retry_service.dto.JobRetryEvent
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Kafka Producer Configuration (for 'run' topic)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Custom Properties
job.retry-topic=retry
job.run-topic=run

retry.redis.zset-key=retry:delayed
retry.dedup.ttl-seconds=600
retry.sweeper.interval-ms=1000
retry.sweeper.batch-size=100
retry.sweeper.lease-duration-ms=30000

# Logging
logging.level.com.zensys=TRACE
