spring.application.name=api-gateway

# Client-facing gateway port
server.port=8080




# Spring Cloud Gateway Routes

# Route GET requests to job-search-service
spring.cloud.gateway.routes[0].id=job-search-read-route
spring.cloud.gateway.routes[0].uri=lb://job-search-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/jobs/**
spring.cloud.gateway.routes[0].predicates[1]=Method=GET

# Route POST, PUT, DELETE requests to job-service
spring.cloud.gateway.routes[1].id=job-write-route
spring.cloud.gateway.routes[1].uri=lb://job-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/jobs/**
spring.cloud.gateway.routes[1].predicates[1]=Method=POST,PUT,DELETE


# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true


# Actuator / Management Endpoints
management.endpoints.web.exposure.include=health,info,gateway